name: Pipeline - Code Testing

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  code-testing:
    name: Invoke Automated Code Testing Template
    uses: ./.github/workflows/templates/template-test.yml
    with:
      python-version: '3.11'
      test-build-docker: false
      artifact-name: 'coverage-report'
