name: Pipeline - Code Deployment (Docker & Azure App Service)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  code-deployment:
    name: Invoke Code Deployment Template
    uses: ./.github/workflows/templates/template-code-deploy.yml
    with:
      acr-name: 'acrteamboarddev'
      webapp-name: 'app-teamboard-dev'
      app-name: 'teamboard'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
