name: Pipeline - Infrastructure (Terraform)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  infrastructure-provisioning:
    name: Invoke Terraform Infrastructure Template
    uses: ./.github/workflows/reusable-infra.yml
    with:
      terraform-version: '1.5.7'
      working-directory: 'infrastructure'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
